### PR TITLE
Lewd Antag

### PR DESCRIPTION
**Pull request by Jay-Sparrow**
## About The Pull Request
It's finally done. Finally.

Simple enough on the user's end. Under preferences you opt in to be the antag, and opt in to be a target.

For admins, you push the create antagonists button and it makes one antag with one random target. Easy as.

If you want to bus it in, you can use the traitor panel and set a specific target for a specific player. NOTE. Every player is on the list. This is an intentional method to bypass the preferences for bussing.

Comes with a specially curated uplink with all the explicitly lethal stuff removed. Fewer TC as well. Should be easy enough to add in custom uplink items in the future.

This code should be serviceable base for future antags like this, with a fairly modular preferences system. Also, now I know how antag code works, I should be able to work on some of the other in work antag projects now.

## Why It's Good For The Game

It's an antag that can be dropped during a greenshift. RP heavy (ideally), and should be fun for the victim too. If this isn't a slam dunk I'm going to be very cross.

## Changelog
:cl:
add: Lewd antag.
/:cl:

### CODE REVIEW

**Comment by Jay-Sparrow** [comment]
Additional note. THIS WON'T HAPPEN ON IT'S OWN. It's admin bus only. Admin must push button. I want supervision for this thing, at least for a while.

**Comment by Kabramen** [comment]
speedmerge  it when

**Comment by Jay-Sparrow** [comment]
aaaaaaaaaaaaaa sorrry

**Comment by Ludox235** [comment]
bruh

**Comment by SaintHusky** [comment]
OwO

**Comment by AbsoluteRawGamer** [comment]
Please off yourselves

**Comment by UncleBourbon** [comment]
⠄⠄⠄⢀⣤⣾⣿⡟⠋⠄⠄⠄⣀⡿⠄⠊⠄⠄⠄⠄⠄⠄⢸⠇⠄⢀⠃⠙⣿⣿
⣤⠒⠛⠛⠛⠛⠛⠛⠉⠉⠉⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠸⠄⢀⠊⠄⠄⠈⢿
⣿⣠⠤⠴⠶⠒⠶⠶⠤⠤⣤⣀⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⠃⠄⠂⣀⣀⣀⡀⠄
⡏⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈⠙⠂⠄⠄⠄⠄⠄⠄⢀⢎⠐⠛⠋⠉⠉⠉⠉⠛
⡇⠄⠄⠄⣀⡀⠄⠄⠄⢀⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠎⠁⠄⠄⠄⠄⠄⠄⠄⠄
⡧⠶⣿⣿⣿⣿⣿⣿⠲⠦⣭⡃⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⡀⠄⠄⠄⠄⠄⠄
⡇⠄⣿⣿⣿⣿⣿⣿⡄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢰⣾⣿⣿⣿⡟⠛⠶⠄
⡇⠄⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣼⣿⣿⣿⣿⡇⠄⠄⢀
⡇⠄⢿⣿⣿⣿⣿⣷⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣿⣿⣿⣿⣿⡇⠄⠄⢊
⢠⠄⠈⠛⠛⠛⠛⠋⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢿⣿⣿⣿⡦⠁⠄⠄⣼
⢸⠄⠈⠉⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠉⠄⠄⠄⠄⢰⣿
⢸⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠁⠉⠄⢸⣿
⠄⣆⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⣀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢸⣿
⠄⢿⣷⣶⣄⡀⠄⠄⠄⠄⠄⠄⠉⠉⠉⠉⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⣴⣿⣿
⠄⢸⣿⣿⣿⣿⣷⣦⣤⣀⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣀⣠⣤⣶⣿⣿⣿⣿⣿

**Comment by basedcringe** [comment]
Big chungus rape antag also shitcode

**Comment by Dahlular** [comment]
Very cool, very mature. You three should go play a game for more your age, because clearly you're not acting like it.

**Pull request merged**
