### PR TITLE
Emote Sound Additions

### PR DESCRIPTION
**Pull request by ProbablyCarl**
## About The Pull Request
This simply adds many new sounds to the in game emotes, while replacing some very old files.
If these are passed, I'll go ahead and do this for _every_ emote that'd be applicable, rather than just a select few.
## Why It's Good For The Game
Not only does it contribute to atmosphere, it allows people to accurately assess a situation within moments instead of having to scan the chat immediately. Not that it's too hard as is, admittedly, given we have Goonchat.
Most importantly, however, it adds Tesh sneezes.
## Changelog
:cl:
add: Provides sounds for most of the primarily used emotes.
add: Provides multiple new emotes.
soundadd: As above, many sounds. They are all exclusively used for emotes.
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
Amazing PR, I'll do an in-depth check later

**Comment by DragonTrance** [comment]
Add teshari sneezes. Now.

**Comment by ProbablyCarl** [comment]
> Add teshari sneezes. Now.

Coming up.

**Comment by DragonTrance** [comment]
FUVKIN HHTYNHNG

**Pull request merged**
