### PR TITLE
Changes the Cremator buttons on Box and Pubby to require Cremator Access

### PR DESCRIPTION
**Pull request by CapnMachaddish**
## About The Pull Request

Exactly what it says in the title. Also adds two pointless and very very minor easter eggs - a pair of renamed sunglasses where the Sec cremator used to be on Pubby (don't worry, only Sec can open the doors, so no randos will be walking in via Maint and getting sunglasses to powergame with), and a couple renamed coins in Maint on Box, because I was really bored.

## Why It's Good For The Game

Removing Security's Cremator discourages incinerating people in violation of Rule 8 (Don't make it harder to clone people), and the same goes for locking the Chapel Cremators on both maps to only people who have Crematorium Access. With any luck, this will discourage wanton incineration and give people more opportunity to roleplay and have fun.

## Changelog
:cl:
del: Security Cremator on PubbyStation
add: A few random harmless renamed items for fun
tweak: Made both Chapel Cremators require Crematorium Access to activate.
/:cl:

### CODE REVIEW

**Comment by CapnMachaddish** [comment]
Ignore the fact that it says the PR was created by "CaptainMegavolt" - that's one of my several other GitHub accounts.

**Comment by CapnMachaddish** [comment]
ATTENTION: DO NOT MERGE THIS!!!
I fucked up and left some shit from testing in, stand by.

**Comment by CapnMachaddish** [comment]
Fuckup corrected, review at your leisure.

**Comment by Chemlight** [comment]
Big thanks for doing this and this overall pull is something I greatly support!

**Review by Dahlular — APPROVED** [review]

**Pull request merged**
