### PR TITLE
box map edit: small science layout change

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
changes some layout of science
littlexenobiochange
littletoxinschange
littlecircuitschange

## Why It's Good For The Game
more functional, subjectively prettier.

## Changelog
:cl:
add: Added roundstart nanite lab
tweak: Changed a little bit of the science layout
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
I'll be honest, I don't know how to feel about roundstart nanites

**Comment by jjpark-kb** [comment]
> I'll be honest, I don't know how to feel about roundstart nanites

any suggestions for a replacement at that spot?

**Comment by jjpark-kb** [comment]
image
changed nanite to this

**Comment by Dahlular** [comment]
That'll do!

**Pull request merged**
