### PR TITLE
We don't need no safety protocols - Merges Random Engines

### PR DESCRIPTION
**Pull request by ArchieBeepBoop**
## About The Pull Request

Ports https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10245 and respective updates by r4d6.

**So, how does it work?** Well, you have a bunch of preset engine maps. The code will, as long as these presets are in game_options.txt, select one of these randomly, based on their weights. Take a look at the changed game_options.txt and familiarize yourself with the names of the engines and the weights available. Certain memey engines are disabled by default. Those are: Budget (PACMAN engines), Triple SM (Three sm crystals) and the empty engine room.

## Why It's Good For The Game

**haha tesla go brrrrrrrrr**

image

image

## Changelog
:cl: r4d6
add: Random Box Station Engines
/:cl:

### CODE REVIEW

**Comment by Jay-Sparrow** [comment]
I say NO. We get delams regularly, we don't need rogue teslas.

**Comment by TotallyNotADog** [comment]
Seconded with Jay. If people aren't responsible enough to set pipes correctly they sure as hell aren't responsible enough to manage a containment field. At least with SM delams the damage is usually only done to the engineering wing, with this the entire station can be destroyed because someone who started playing SS13 5 minutes ago didn't know to turn on the containment field emitters.

**Comment by ArchieBeepBoop** [comment]
All I'll say is, we shouldn't be evening out the odds based on incompetence. We have a lot of very competent people as well that know how to set these up and teach as well. I do not think anyone who's sane enough will pick engineer for their first time playing SS13 or try to mess with a tesla without at least reading the wiki on how to set them up, as that's an excellent way to get a job ban. Ts cannot even cause delams without being bonked, I can't imagine they would be able to cause a tesloose or singuloose and not get bonked as well.

Overall, I do like the ability to be able to have _**some sort**_ of randomness to box station since that's the only station this playerbase really plays/enjoys, as we don't have delta or meta or any other stations than pubby in our rotation, even though some of those were fixed.

There should be an effort to encourage people to learn new things and not be locked in the same box. (Pun not intended)
There are, however, those who refuse to learn how to set up a proper, safe setup and to acknowledge that what they were doing was wrong, but that can be easily solved with a job ban if that's the case.

**Comment by Jay-Sparrow** [comment]
The competent engineers don't matter when a newbie pushes a button they don't understand. I don't know what else to say. The SM explosion is at least usually contained to the engineering room. This is just adding chaos so that the engineer does something slightly different at the start of the shift before leaving the engine unattended to go hang out.

**Comment by ArchieBeepBoop** [comment]
> The competent engineers don't matter when a newbie pushes a button they don't understand. I don't know what else to say. The SM explosion is at least usually contained to the engineering room. This is just adding chaos so that the engineer does something slightly different at the start of the shift before leaving the engine unattended to go hang out.

Out of all these, the only one you have to babysit constantly is the singulo because of their constant size difference, I believe. While yes, the SM explosion is usually contained to the engineering room, the singulo can be contained with well placed bags if someone really fucks up. Also, any engineer that sets up a singulo/tesla has to know what they're doing as they still have to set up the entire particle accelerator and someone who doesn't know will likely not know how to piece it together.

I think we should at the very least try this. Maybe reduce the weight of the singulo if need be but... I really want to see some sort of difference when I do engineering.

**Comment by CapnMachaddish** [comment]
I'm somewhat with Archie on this one - people need to learn somehow, and frankly, if newbies are wandering out into reactor control and deactivating/activating parts of a machine that looks big, flashy and dangerous, that's a bigger problem that needs to be addressed elsewhere.

**Comment by quotefox** [comment]
Tesla pretty sus.

I'm actually okay with this, things SHOULD be dangerous in the station, hand holding is fucking bad in my opinion, makes things dummer, and people should learn. 

Plus tesla. I miss you. 
I'll have an open discussion with the admins and users for this soon.

**Comment by Moltovz** [comment]
Most folks on this station can't remove volume pumps from an N2 setup. Other engine's will certainly allow engineers to learn more, but that process of learning how to setup new engine types will most likely cause a few singlos to go loose. Speaking of- If you merge this, give the CE, Captain, fuck it- EVERY HEAD a singlo-buster. The singularity is awfully easy to free, and I doubt engineers will go to the engine every ten minutes to make sure the field is charged, and emitters are firing.

**Comment by Dahlular** [comment]
Personally, I'm fine with more engines. It gives me, an admin, a hell of a lot more of a reason to punish people harder when they delam a tesla or singularity. My biggest problem with people on-station right now is those who genuinely are afraid of the Supermatter and do not know how to set it up, so they find reason to bash those who do set it up. I do not want to hold hands because "WELL WHAT IF THE SINGULO GETS OUT?!", when those things getting out shouldn't happen anyways. 

You should know damn well how to do your job if you're doing things with a tesla and singulo. If not, I am glad to hand out more jobbans. Solars are still available, you don't HAVE to set up this engine, either.

 Also, comment above hidden because Moltov is permabanned and doesn't need to donate to topics here.

**Comment by ArchieBeepBoop** [comment]
Keep in mind this still needs to be properly testmerged. I tested some of the engines so far and they spawned successfully, but issues could happen. At least it's easily reverted as long as no one touches the box station map.

**Comment by Burns-The-Potatoes** [comment]
The supermatter is the easiest to mess up in a dangerous way. Adding randomized engines will entice new engineering players to learn, and also be incredibly funny if they forget to wrench a forcefield, while simultaneously bringing variety to occasionally boring shifts.

Focusing on the fact that delaminations happen sometimes is kind of stupid, as we may as well just remove the supermatter engine if we really care about that.

**Pull request merged**
