### PR TITLE
Beat each other with a horse dildo

### PR DESCRIPTION
**Pull request by ArchieBeepBoop**
## About The Pull Request

Adds a unique dildo that finally allows your dreams of beating someone to death with a gigantic, flared and comically oversized horse cock dildo. Why? Well, blame dahl.

## Why It's Good For The Game

no

## Changelog
:cl:
add: 11 brute force to a fucking rubber cock.
/:cl:

### CODE REVIEW

**Comment by TotallyNotADog** [comment]
add damage to the bitch breaker too maybe? hmmmmmmmmmmmmmmmm

**Comment by ArchieBeepBoop** [comment]
done

**Comment by Dahlular** [comment]
why

**Comment by ArchieBeepBoop** [comment]
fixed

**Comment by quotefox** [comment]
Give it a handle, and holding sprite, and make it contraband, I'm all down. 

Its good practice to have the characters sprites holding a weapon that can damage you.

**Comment by Moltovz** [comment]
player default clone
How the fuck do you make a horse cock not look like a sword help I'm dying

**Comment by ArchieBeepBoop** [comment]
> Give it a handle, and holding sprite, and make it contraband, I'm all down.
> 
> Its good practice to have the characters sprites holding a weapon that can damage you.

I did make it contraband for sec vendor but I made it a premium on the kink vendor (only one available and costs a coin)

I'd love to have a proper sprite for it, yeah. I know this PR is dumb and something that was done while I was rather inebriated with lack of sleep, but hey.~

**Comment by Chemlight** [comment]
Honestly considering it's an object made of soft materials, I want to say it should do stamina damage on top of arousal damage, just so if someone doesn't like it they can scream sexual assault over actual assault.

**Comment by ArchieBeepBoop** [comment]
I mean, the harming one is literally described as being the opposite of soft.

**Pull request closed without merging**
