### PR TITLE
Ports Long Range Gas Analyzer

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
CE starts with this, or can be printed by protolathe after unlocking advanced tools.
This scans gasses on a turf when scanning a clicked turf in your view

## Why It's Good For The Game
Hask asked me to do this PR

## Changelog
:cl:
add: Added Long Range Gas Analyzer, CE starts with it, otherwise can be printed after unlocking power tools
/:cl:

### CODE REVIEW

**Review by Dahlular — APPROVED** [review]
thank u azzy

**Comment by Azarak** [comment]
fuckin what did i do 1 moment

**Comment by Azarak** [comment]
why does git show so many changes if only i changed 1 line in the belt.dm what

**Comment by Azarak** [comment]
i'll just make a new PR

**Pull request closed without merging**
