### PR TITLE
Reworks Dwarfism, Adds Giantism, Bluespace Compression Shrinking, and Makes Sizechems Craftable

### PR DESCRIPTION
**Pull request by Dahlular**
## About The Pull Request
Removes the pass_table flag from dwarfism and the flat transform; instead applies a size_multiplier change to it. Adds a new genetic trait being Giantism, which is the opposite of dwarfism. 
Removes functionality of Growthserum.
Makes it so Bluespace Compression Kits can shrink people too
As well as that, makes size chemicals craftable through some Fermichem fuckery; recipes and values are subject to change.

RECIPES:
**Cell-Volume Altering Base**
1 part growthserum, 1 part clonexadone, 1 part gold, 1 part acetone. Optimal temperature at 600-300K, explodes above 635. Optimal pH of 5-5.5. No inverse or impure effects yet.

**Prospacillin** (Growth Chem)
1 part cell-volume altering base, 1 part condensed capsaicin, 2 parts aphro. Optimal temperature at  700-730K, explodes above 735. Optimal pH of 3-3.5. No inverse or impure effects yet.

**Diminicillin** (Shrink chem)
1 part cell-volume altering base, 1 part frost oil, 2 parts aphro. Optimal temperature at 100-150K, explodes above 350. optimal pH of 3-4.5. No inverse or impure effects yet.

## Why It's Good For The Game
Gives people a way to finally change their sizes in-game, albeit through harder to obtain mechanics.

## Changelog
:cl:
add: Prospacillin recipe
add: Dimicillin recipe
add: Sizechem
add: Giantism
add: Bluespace compression Kit shrinking people
del: growthserum effects
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
dadfox said yes, time to merge

**Comment by quotefox** [comment]
I said yes, time to merge

**Comment by Dahlular** [comment]
time to cum

**Comment by Moltovz** [comment]
imagine trying to make the funny growth chem and you **fucking explode**

**Pull request merged**
