### PR TITLE
[Proposal] Reduces inject time for hypospray + apply time for defib shock + balance emagged defibs

### PR DESCRIPTION
**Pull request by ArchieBeepBoop**
## About The Pull Request

Reduces the application time for the defib and hypospray slightly, while buffing the emagged/combat defibs to be able to disarm shock others instantly. (Stamina damage)

## Why It's Good For The Game

While I am definitely against making these instant, -maybe- they should be buffed slightly. Perhaps a test would be good. See if people are powergaming the fuck out of it or not.

As for the emagged defib, well, we have limited use emags unlike other codebases, so you should be able to make those uses actually count for something. Emagged defibs, before this PR, did nothing but have their safeties disabled, which was something that could be done using an EMP. Now emags turn on the combat flag and release the safeties.

## Changelog
:cl:
balance: decreased application times for the hypospray and defib paddles slightly.
balance: emagged defibs can disarm shock instantly.
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
So-so on this one. I don't think this is entirely necessary, it just feels like power creep for medical players that have nothing to do.

**Comment by ArchieBeepBoop** [comment]
> So-so on this one. I don't think this is entirely necessary, it just feels like power creep for medical players that have nothing to do.

Maybe just the defib emag function then? Currently emags to the same as EMPs on them. This would still keep the heart attack (harm function) delayed, but the stun one (which works as a basic stunbaton) instant, yet still with the recharge.

**Comment by Dahlular** [comment]
Ehhh, I'd prefer not. Defibs aren't weapons.

**Comment by ArchieBeepBoop** [comment]
> Ehhh, I'd prefer not. Defibs aren't weapons.

I mean, overall balance-wise I think it's pretty okay, as we have limited emag uses and this should likely be a last resort thing, as a stunbaton is -much- better than this. I think of it as a wildcard of sorts for a medical doctor traitor, as they still won't be able to carry around a bag, even.

**Pull request closed without merging**
