### PR TITLE
Updates the code to latest cit vertion [DNM]

### PR DESCRIPTION
**Pull request by LetterN**
## Changelog
:cl:
add: TGUI-next
add: Public Lavaland mining
add: Modular engine (Box only!)
add: Gangs
add: Vamps
tweak: Reagents are now datum-based
code: LF Line endings
code: 513 Support
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
BLESSED

**Comment by Dahlular** [comment]
JESUS CHRIST

**Comment by quotefox** [comment]
Lord have mercy, get this guy a medal.

**Comment by Investigator77** [comment]
LEGENDARY

**Comment by BobJogaIsForkinBanned** [comment]
ABSOLUTE FUCKING MADMAN

**Comment by Dahlular** [comment]
This has been sat on DNM for a while. Closing.

**Pull request closed without merging**
