### PR TITLE
More Box Improvements and Cleanup

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

I fixed some things with box, after comparisons with Yog / Bee box.

Also removed the redundant extra box map from the root of the game folder, from someone else's previous attempt at mapping.

## Why It's Good For The Game

Sergeant-at-Armsky is every Warden's best friend, and every unrobust traitor's worst nightmare. This little lad provides extra security to the armory and has been known to be the most robust bot among other servers. Currently, Armsky is set to Detain, and checks for warrants, weapon permits, and unidentifiable persons, using Bee's Armsky for reference.

image

I also restored Dorm 1. This provides another safe room for people to do their business. The previous work done was honestly, sloppy, considering that whoever did it didn't even rename the three remaining dorms (cabins don't count), so dorms 2 - 4 existed but not 1.

image

Cryosleepers were moved to the north side of the fitness room, and is powered by the APC for fitness. A large room is not needed for cryosleepers and considering the pods empty shortly after someone ghosts in it, you don't need to have an excessive amount of pods. VR sleepers were also removed, considering they are never initialized so there is no reason to have them in the first place if they are never going to be running. 

image

## Changelog
:cl:
add: Sergeant-at-Armsky, the robust secbot protects the Armory. 
remove: VR sleepers from Box.
tweak: Dorm 1 restored. Cryosleep was moved towards
fix: Cleaned up some area code. There were a few locations, such as part of the morgue, that were mislabeled.
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
Finally, a reliable warden for the armory

**Comment by Dahlular** [comment]
Also for future reference if you're gonna make a dumb asshole containment, at least put it it in the changelog lol

**Comment by SynnGraffkin** [comment]
Learn how to skim through code then. It isn't hard to see what green adds and what red removes. You're probably taking too much time blindly merging horny code that you can't see the big green block with your name literally in it. Also, thanks for just saying I "left" the discord. Truly the Dahl way. Cover up and don't question authority of the Yeen. Totally not because you kicked me the first time for proving, once again, you don't like discussion about policy change and now just a straight up ban when I've just been chilling in the welcome room after you found this.

image

**Comment by Dahlular** [comment]
image

**Pull request merged**
