### PR TITLE
Layenia Station

### PR DESCRIPTION
**Pull request by Dahlular**
## About The Pull Request
image

Introducing Layenia Station, a station built within the floating upper atmosphere of a gas giant. Bluespace and plasma research have long since been already tapped by the likes of Kinaris; focus now is presented to Lattice Crystals. 

This station is primarily to switch things up and set aside most standard TG gameplay elements. I must stress this, this station was **NOT** designed for standard SS13 gameplay; this was moreso designed with Hyperstation's community and playerbase in mind-- if you plan on porting this, I deeply apologize for immense shitcode, but keep that in mind.

**THIS MAP WILL 100%, MOST DEFINITELY HAVE SOME ISSUES. THESE WILL BE FIXED DOWN THE ROAD, PLEASE KEEP THIS IN MIND. SOME SPRITES ARE NOT FINAL, AND SOME THINGS (like solars) WILL NOT WORK.**

## Why It's Good For The Game
Hyperstation's own unique map.

## Changelog
:cl: Dahlular, Toonclyde, Quotefox
add: A new station
add: More parallaxes
add: Railings from virgo
add: Layenia rocks, layenia crystals
/:cl:

### CODE REVIEW

**Comment by DragonTrance** [comment]
Rip to the conflict

**Comment by Dahlular** [comment]
workin on it

**Comment by Dahlular** [comment]
mfw wrong branch

**Comment by Dahlular** [comment]
dad said i could merge, lets get these bugfixes on the road

**Pull request merged**
