### PR TITLE
stinky blacklist

### PR DESCRIPTION
**Pull request by lyricalpaws**
## About The Pull Request
Actually removes the wishgranter cube from spawning because evidently the blacklist doesn't work

## Why It's Good For The Game
I was trying to do this already, so lets make it actually work

## Changelog
:cl:
tweak: Comments out the wishgranter ruin from spawning
/:cl:

### CODE REVIEW

**Comment by DragonTrance** [comment]
Instead of just commenting it out, why not try and make the blacklist work

**Comment by lyricalpaws** [comment]
> 
> 
> Instead of just commenting it out, why not try and make the blacklist work

Because the code I'm looking at should work, but for some reason doesn't. So it's either an issue I can't see, or an issue with the host server not updating configs. In either case, it's way easier for me to just comment out the offending ruin.

**Comment by lyricalpaws** [comment]
^ Fixing sprites that were bugged that got introduced with a related pr

**Comment by Dahlular** [comment]
Juuust barely updated config files serverside. PR not needed now?

**Comment by lyricalpaws** [comment]
> Juuust barely updated config files serverside. PR not needed now?

Yeah feel free to close it, if the cube ruin is uncommented then it should stop spawning

**Pull request closed without merging**
