### PR TITLE
Adds condiment bottle sprites and descriptions for the three jellies

### PR DESCRIPTION
**Pull request by VladinXXV**
## About The Pull Request
The three jellies in the game, slime jelly, cherry jelly, and blue cherry jelly, lack their own condiment bottle sprites and descriptions. An absolute outrage! Who the hell stores jelly in unlabeled grey bottles? This PR gives them comfy jars that are appropriately labeled.

## Why It's Good For The Game
Improves the quality of our kitchens, and also helps prevent condiment mixups. God forbid the chef give you slime jelly instead of cherry jelly on accident because they're the same color in beakers and the same dull grey condiment bottle.....

## Changelog
:cl:
imageadd: Adds the Slime Jelly Jar, Cherry Jelly Jar, and Blue Cherry Jelly Jar condiment bottle sprites.
add: Adds descriptions for said Jelly Jars.
/:cl:

jelliemoment
_Pictured: The three jelly jars and their predecessors placed on a metal table._

### CODE REVIEW

**Comment by VladinXXV** [comment]
Explaining the color choice for jelly:
That's the actual color assigned to the reagents. Cherry jelly and slime jelly have the **_EXACT SAME_** color, and for some god forsaken reason the dark blue cherries make neon blue jelly that reminds me of Nuka Cola Quantum, hence the different packaging.

**Comment by TotallyNotADog** [comment]
this is all a webedit and i despise you for it

**Comment by VladinXXV** [comment]
> this is all a webedit and i despise you for it

love you too babe

**Review by Dahlular — APPROVED** [review]
jelly

**Pull request closed without merging**
