### PR TITLE
tasty carbon nanotube noodles

### PR DESCRIPTION
**Pull request by ToonClyde**
## About The Pull Request
some tasty spicy noodles with a small amount of charcoal in it to cure a little bit of toxin damage (please don't kill me Dahl!!)
they can be found in the premium slot in vending machines

(the icon is a work in progress it may or may not be improved depending on feedback)

## Why It's Good For The Game
it's good if you're on one of those charcoal diets and just more funny snacks

## Changelog
:cl:
add: Adds carbon nanotube noodles to snack vending machines
/:cl:

### CODE REVIEW

**Comment by ArchieBeepBoop** [comment]
HA

**Comment by Dahlular** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by ToonClyde** [comment]
kehe please come on it actually is a proper working thing

**Review by Dahlular — APPROVED** [review]

**Comment by CapnMachaddish** [comment]
This is legendary

**Pull request merged**
