### PR TITLE
Temporarily removes sentience events

### PR DESCRIPTION
**Pull request by Jay-Sparrow**
## About The Pull Request

Gets rid of sentience events until I figure out what to do with them.

## Why It's Good For The Game

Emergency hotfix.

## Changelog
:cl:
del: Remove Random Sentience Event
/:cl:

### CODE REVIEW

**Comment by ArchieBeepBoop** [comment]
This is not needed, it was not random sentience. The prompt for random sentience is "Random animal"  This was specifically targeted at a giant spider, as the prompt was "do you want to play as a giant spider"

**Comment by ArchieBeepBoop** [comment]
Also, friendly reminder that there's a blacklist that I made for random animal sentience, which could be used instead if you're adamant on that. Refer to PR: https://github.com/quotefox/Hyper-Station-13/pull/655

**Comment by Jay-Sparrow** [comment]
I'm doing homework right now, I'll get this rebalanced later. This is temporary.

**Comment by ArchieBeepBoop** [comment]
no longer needed?

**Comment by Dahlular** [comment]
No longer needed

**Pull request closed without merging**
