### PR TITLE
Various (small) Botany Changes

### PR DESCRIPTION
**Pull request by DragonTrance**
## About The Pull Request
- Tea now mutates into astra or catnip, instead of Tea > Astra > Catnip, since one is undoubtedly better than the other in some way. As such, Tea Astra no longer mutates into catnip.
- Spam-clicking with mutagen on a plant makes it no longer detectable that it's already mutated ("uses the bucket on gaia" > "deus mutates into gaia")
- Fixes some plants not adding reagents, i.e. spaceman trumpet

## Why It's Good For The Game
Provides fixes for plants, flexibility for customization in the future if we wanna do anything fancy when a plant mutates, encourages people to grow catnip more, and makes mutagen a teeny bit harder to manage by hiding that the plant had already mutated before it tells you in the chat "Deus suddenly mutates into Gaia!"

## Changelog
:cl:
add: catnip uses the icons from regular tea now, instead of no icon. this is temporary until I can find a proper icon for catnip, or until someone from the discord is willing to make sprites
add: seeds now have mutatespecie() for special actions to execute when the seeds mutate into a different species. In case we wanna do any fancy stuff
add: some defines in hydroitemdefines.dm. I know this isn't what the file is for, but I got compile errors otherwise
add: Admin-only spawn of a plant that shows off what interesting things the mutatespecie() proc could do (chaos_shroom.dm), dont spawn it cause if it does work as intended (which i TOTALLY didn't check), it makes a big explosion when mutated
balance: Pink Peppers produces 4% incubus instead of 8% and cannot be extracted
balance: Milk Melons produces 4% succubus instead of 8% and cannot be extracted
fix: some plants not adding the correct reagents from genes
code: organized a few things
code: /obj/item/seeds/ now uses mutate_factor, see hydroitemdefines.dm for more info
/:cl:

### CODE REVIEW

**Comment by ArchieBeepBoop** [comment]
No, we already went over this, they were placed in xenoarch for a reason.

**Comment by DragonTrance** [comment]
> No, we already went over this, they were placed in xenoarch for a reason.

Nobody goes down to xenoarch at ALL anymore. Most of the time you'll just get toys or low-valued things to sell

**Comment by ArchieBeepBoop** [comment]
Xenoarch gives people a fantastic research point output, on top of one being able to find a lot of **gamer items** already. It's not just toys. 

While people cannot control themselves to rush botany pink peppers and milk melons, I will be completely against this.

**Comment by DragonTrance** [comment]
> Xenoarch gives people a fantastic research point output, on top of one being able to find a lot of **gamer items** already. It's not just toys.
> 
> While people cannot control themselves to rush botany pink peppers and milk melons, I will be completely against this. Leaving it in xenoarch makes them actually have to go through some effort instead of spamming mutagen until they get it and also allows them to interact with science.

Fair enough, you've convinced me. Imma change the pr later to get rid of the mutations. I knew the point they were removed before was because people rushed botany and ONLY made lewd stuff. I'll keep all of the other stuff though so you cant put the lewd chems into other growns

**Pull request closed without merging**
