### PR TITLE
Mining balance changes, some new icons, and good stuff.

### PR DESCRIPTION
**Pull request by lyricalpaws**
## About The Pull Request
Rebalances a few aspects of lavaland, replaces one ruin with another, adds some new cursed trinkets, and some icons for items.

## Why It's Good For The Game
Lavaland has needed a little kick honestly, this is a step towards that.

## Changelog
:cl:
mapadd: Lust ruin
add: Lust chalice/fountain
add: CE's insulated gloves skin
add: Framework for concussive gauntlets
add: New tendril loot
add: miner version of ert hardsuits 
tweak: ert hardsuit protection values for miners
tweak: nerf legion core healing and moodlet
maptweak: Changes the chapel slightly
mapremoval: Removes wish granter ruin from spawning
removal: blood red hardsuit legion corpse no longer spawns
/:cl:

## Credits
@CapnMachaddish - Lust Chalice sprite
/TG/ Station - CE insuls sprite

### CODE REVIEW

**Comment by lyricalpaws** [comment]
ah shit, map conflict. Fixing now

**Comment by lyricalpaws** [comment]
why does it keep conflicting I just updated the map

**Comment by lyricalpaws** [comment]
dies dies dies
it worked

**Comment by ArchieBeepBoop** [comment]
Why is the Nar'sie hardsuit being changed?

**Comment by lyricalpaws** [comment]
Accident, ert were supposed to be but not cult. WIll fix shortly

**Comment by lyricalpaws** [comment]
Ready now

**Comment by ArchieBeepBoop** [comment]
Contrary to popular belief the wishgranter does not make you an antag. It gives you three options, a battery that never runs out, a sword, becoming a gold golem or going blind. There's no reason to blacklist.

**Comment by lyricalpaws** [comment]
> 
> 
> Contrary to popular belief the wishgranter does not make you an antag. It gives you three options, a battery that never runs out, a sword, becoming a gold golem or going blind. There's no reason to blacklist it.

Regardless, Dahl and several others have expressed views against it. Not to mention it's a holdover from TG, and doesn't really fit hyper.

**Review by Dahlular — APPROVED** [review]
This is a very good PR

**Pull request merged**
