### PR TITLE
guardian "rework"

### PR DESCRIPTION
**Pull request by SmeagleDeagle**
It's not ss13 without scuffed ports, this ports some fuckin better guardian/holoparasite systems from Yogstation....

(may contain rabid shitcode)

:cl:
added a small chance of stand arrows from certain meteors
fucked up some other things so all sources of natural stands give randomly made stands. It's not a bug, it's a feature!
new stand abilities, I guess?
requiem stands
i'm tired, figure the rest our yourself
/:cl:

"You want fun? Wario show you fun!"

### CODE REVIEW

**Comment by Dahlular** [comment]
In the future, please format your PRs correctly.

**Comment by The-Sun-In-Splendour** [comment]
in the CL you're supposed to add stuff like :add: :del: etc etc
by the way can you please actuaully explain what the fuck you changed in the PR

**Comment by Dahlular** [comment]
^ This, holy shit

**Comment by SmeagleDeagle** [comment]
Method used to choose stands uses tgui 4, fuck it.

**Pull request closed without merging**
