### PR TITLE
Various lavaland related changes

### PR DESCRIPTION
**Pull request by lyricalpaws**
## About The Pull Request
1) It makes the xeno microbes from the hive's blessing turn you in to a ~~larvae~~ sentinel rather than a xeno hunter, and adds a gps (Distress Signal) to the hive.

2) Gives BDM a custom kinetic accelerator with 200% mod capacity

3) Lets you make hell water (Holy water at ~~700~~ 666 kelvin, 1:1 conversion)

## Why It's Good For The Game
More choice for non antag xeno, and lets miners find the hive ruin easier, rather than stumbling on it.

BDM's KA was useless before, now it's cool

We couldn't make hell water for a cool cult chapel, now we can

## Changelog
:cl:
change: xeno hunter to larvae
add: miner gps (distress signal) to the hive, on top of all the miner gear in the queen nest
add: Recipe to make hell water from holy water
add: BDM custom KA
change: BDM now drops a custom KA
/:cl:

### CODE REVIEW

**Comment by CapnMachaddish** [comment]
"Boil the hell into it"

This is the shit I live for

**Comment by Kabramen** [comment]
image

Perfect

**Comment by Kabramen** [comment]
also, maybe you should change from 700 kelvin to 666 kelvin, for maximum hellmeme

**Comment by lyricalpaws** [comment]
> 
> 
> also, maybe you should change from 700 kelvin to 666 kelvin, for maximum hellmeme

Funny

**Comment by lyricalpaws** [comment]
Based on opinions from others, changed larvae to sentinel, a nerf if anything.

**Pull request merged**
