### PR TITLE
Adds a *bruh emote

### PR DESCRIPTION
**Pull request by Dahlular**
## About The Pull Request
Adds a completely necessary *bruh emote for people to define their bruh moments with.

## Why It's Good For The Game
Enriches people's experiences whole-heartedly with the definition of bruh momentum in audible form. Those who miss such bruh moments can only weep and sow the seeds of regret in their heart.

## Changelog
:cl:
add: bruh
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
Haha gimme a damn second, my OCD is fucking me UP

**Comment by Dahlular** [comment]
OKAY ITS FIXED I KNOW HOW DUMMY I AM, should be good to go

**Comment by DexterDude** [comment]
no

**Comment by Dahlular** [comment]
> no

Suffer, mortal.

**Comment by deathride58** [comment]
ｂｒｕｈ

**Comment by Dahlular** [comment]
> ｂｒｕｈ

ｂｒｕｈ ｓｏｕｎｄ ｅｆｆｅｃｔ ２

**Pull request closed without merging**
