### PR TITLE
SHITPOST STATUS

### PR DESCRIPTION
**Pull request by MalricB**
## About The Pull Request

1 (one) **w**holy shit

## Why It's Good For The Game

1 (one) **w**holy shit

## Changelog
:cl:
add: quotefox is now whole
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
WHOLY SHIT I BEAT YOU TO IT

**Comment by MalricB** [comment]
YEENFRE BEAT ME TO IT ARHRHGRHG

**Comment by MalricB** [comment]
FUCKSTICK

**Comment by Dahlular** [comment]
ARHARJHJHGKFGFH

**Pull request closed without merging**
