### PR TITLE
Junior roles

### PR DESCRIPTION
**Pull request by Jay-Sparrow**
And more! Oof ouch my soul.

## About The Pull Request

Adds in junior roles. These jobs are at most locked behind crew time.
All other roles are locked behind the junior roles, so you have to play a couple rounds with the giant "I'm new here" tag.
Also, GREATLY increases the time needed to unlock jobs, especially head roles.
Also, cleans up some files that were weird and I hated on the basis they made things kinda hard to read.

## Why It's Good For The Game
WE'VE GOT SOME VERY INEXPERIENCED NEWBIES TAKIN CAPTAIN.

## Changelog
:cl:
add: Junior jobs
tweak: unlock times
/:cl:

### CODE REVIEW

**Comment by ArchieBeepBoop** [comment]
at what cost jay

**Comment by DragonTrance** [comment]
Imagine taking a junior role

**Comment by quotefox** [comment]
perhaps replace junior with trainee?

juniors scare me

**Comment by Jay-Sparrow** [comment]
Junior is just the name of it in the code. The titles in game will read
-Engineering Intern
-Research Student
-Medical Resident
-Rookie

**Review by Dahlular — APPROVED** [review]

**Pull request merged**
