### PR TITLE
Adds horns options to every species

### PR DESCRIPTION
**Pull request by Aphast**
## About The Pull Request
Enables horns for all species minus xeno,ipc,plas,and shadow. ipc plasma and shadow are mainly due to not having the actual options and xeno seems to be bugged. This also adds in some ribbon options for those who want more than the spawn-only simplemob

## Why It's Good For The Game
more horns is better no? plus adding 2 new wing types and horns

## Changelog
:cl:
add: sylveon ribbons
tweak: horn option enabled on most roundstart species
/:cl:

### CODE REVIEW

**Comment by Aphast** [comment]
Currently xenos are unable to have horns aswell as the new wing option not displaying at all on sprite, otherwise seems to be good from some quick testing

**Comment by Aphast** [comment]
New stuff works now, all species have horns and can spawn with them in the random button, and the new sprites display properly simmilarly to wings. xenos seem to be just unable to have horns due to other options and ipcs, plases, and shadows dont have customization at all or for the same slots

**Review by Dahlular — APPROVED** [review]

**Comment by Dahlular** [comment]
Seems fine tbh, could think about adding those in later.

**Comment by Aphast** [comment]
> 

neat, if theres any conflicts or further revisions needed lmk

**Pull request merged**
