### PR TITLE
Nerfs research point generation from bz

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request

Makes the research point gain from various gases 10% of the previous in order to prevent research being rapidly completed.

## Why It's Good For The Game

No more all technology done in 10 mins.

## Changelog
:cl:
balance: Nanotrasen has learned enough about the synthesis of various gases.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Dont know why you'd change noblium research. Takes around 40 minutes of non stop work to make some

**Comment by Azarak** [comment]
but yeah good PR anyway

**Comment by SynnGraffkin** [comment]
At least make it half. Don't think it needs to be 1/10th the amount.

**Comment by shellspeed1** [comment]
It's 1/10th for right now, mostly to see how fast people can get research done. Research should take at least an hour without a bomb. It should still be pretty fast.

**Comment by shellspeed1** [comment]
1/10th of the previous rate is fine, you can still boost research pretty hard, but you gotta now compensate for the traits of each gas and it's formation, for example bz heating up a room, or the difficulty of generating miasma.

**Comment by shellspeed1** [comment]
1/10th of the previous rate is fine, you can still boost research pretty hard, but you gotta now compensate for the traits of each gas and it's formation, for example bz heating up a room, or the difficulty of collecting enough bodies for miasma.

**Pull request merged**
