### PR TITLE
 Nerfs RLDs because they hard counter nightmares and night ops.

### PR DESCRIPTION
**Pull request by ArchieBeepBoop**
## About The Pull Request

Ports https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10586
Reduces RLD matter capacity from 500 to 240
Reduces RLD matter increase per sheet from 16 to 8
Increases RLD wall Light construction costs from 10 to 20 (50 uses -> 10 uses)
Increases RLD floor light construction costs from 15 to 20 (~35 uses -> 10 uses)
Increases Light launch cost from 5 to 30 (100 uses -> 8 uses)

Costs will probably need adjustment, but are leaning towards the harsher end for now. Ideally they should be on par with RCDs in terms of costs and benefits.

## Why It's Good For The Game

Rapid Light Dispensers are currently very overpowered because of their ability to effectively spam maintenance with a flood of lights that antagonists/nightmares really cannot compete with. Darkness can be a very important tool for antags and removing that so easily with a single RLD capable of lighting up entire halves of maint is just not fun. It doesn't help that it's cheap as hell to do so in both mats and credits.
Not only that, having 500+ glowsticks thrown around fucks up the lighting system.

## Changelog
🆑
balance: RLDs now cost more to use, have reduced matter capacity, and sheets are worth less when refilling them.
/🆑

### CODE REVIEW

**Comment by Dahlular** [comment]
For an item that you need to buy to even get on station, this feels a bit excessive, especially considering how much of a royal pain in the ass nightmares can actually be (ever had a nightmare go out of their way to smash every SMES on the station and delam the supermatter?)
I do agree with some of these, but I believe that this direct port from Citadel doesn't fit Hyper. If you can perhaps make the light-launch costs along the lines of 30 uses rather than 20, as well as probably put the matter per sheet to something like 8 rather than 5. Otherwise, this is a necessary change, at least somewhat.

**Comment by Dahlular** [comment]
And before you ask, yes, I'm biased because I used a light launcher only to kill a nightmare and it was the funniest thing on the planet

**Comment by ArchieBeepBoop** [comment]
I mean, we still have the old nightmare which has a light eater that doesn't destroy APCs in three hits and all that, but, welp.

Changed the costs.

**Comment by Dahlular** [comment]
Yeah, but nightmares on their own are absolutely ridiculous already, especially for our coombrained population.

**Review by Dahlular — APPROVED** [review]

**Pull request merged**
