### PR TITLE
Addition of a milk cleanable decal

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

Milk cleanable decal, which occurs whenever milk is spilt or a player masturbates/climaxes with their breasts.

## Why It's Good For The Game

Additional consistency with other genital fluids which also produce messes when used.

## Changelog
:cl:
add: Milk can now form a mess on the floor when spilled or produced in some manner.
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
Chad.

**Comment by Dahlular** [comment]
Appears to not work consistently; only spawning the decal when it's in a container that is spilled... At least from what I've tested. Is that intentional?

**Comment by jbox144** [comment]
> Appears to not work consistently; only spawning the decal when it's in a container that is spilled... At least from what I've tested. Is that intentional?

No. From my testing it should be triggered by normal arousal actions. I'll look further into the changes and see if anything is missing (the change is largely a copy and paste of the semen and ejaculate code)

**Comment by Dahlular** [comment]
Right, I'm assuming there's a threshold for actually spawning the cleanable much like semen decals. All I needed to know, I'll merge this here soon!

**Comment by jbox144** [comment]
> 
> 
> Right, I'm assuming there's a threshold for actually spawning the cleanable much like semen decals. All I needed to know, I'll merge this here soon!

Ah yes. That's to avoid tiny amounts of materials being spread out by insane margins and spammed. At least I think so.

**Pull request merged**
