### PR TITLE
You can finally go to Brazil (Brazil Shuttle)

### PR DESCRIPTION
**Pull request by ArchieBeepBoop**
## About The Pull Request

Adds the Brazil shuttle.

## Why It's Good For The Game

That's an interesting question. It was more of a "By popular request on general chat" thing.

## Changelog
:cl:
add: Brazil Shuttle
/:cl:

### CODE REVIEW

**Comment by TotallyNotADog** [comment]
ALERTA DE MACACO

ALERTA DE MACAAAAAAAAAAAAAAAAACOOO

**Comment by VladinXXV** [comment]
OOO AAA OOO AAAAAAHA HAHAHAAAAAAAAAAAAAAAA MONKE FLIP

**Comment by Kabramen** [comment]
In all honesty I'm not against making a meme Brazil shuttle, but judging by the screenshot posted in discord, this makes me cringe in the current state.  It has little to do with Brazil and even has some stuff that makes no sense to be in there (like gorillas). Brazil has way more things that could be used to make fun about, but right now this look like a cheap joke for me.
 
Unless it gets renamed to jungle shuttle (since that's what looks like), i think it needs way more work.

**Comment by VladinXXV** [comment]
Well to be fair, this started off my suggestion of a "jungle shuttle"

**Comment by ArchieBeepBoop** [comment]
I'm all in to put actual skol and Brahma/skol tables and plastic chairs everywhere alongside a few footballs. But yeah this did start as jungle shuttle but evolved into the brazil shuttle meme. 

I'd love to have people sprite stuff like a cavaquinho, those big red signature bricks and etc to just lay them around.
It'd actually make the shuttle a bit more chill and less empty.

**Comment by Kabramen** [comment]
also you didn't used thee macaco soup that I added here smh https://github.com/quotefox/Hyper-Station-13/pull/22

**Comment by ArchieBeepBoop** [comment]
> also you didn't used the macaco soup that I added here smh #22

fug, I will add it

**Comment by Dahlular** [comment]
i really don't know if i can muster the energy to approve or close this

**Comment by ArchieBeepBoop** [comment]
You must do it for the unga

**Comment by ArchieBeepBoop** [comment]
> i really don't know if i can muster the energy to approve or close this

for the unga, dahl

**Pull request closed without merging**
