### PR TITLE
Sounding Rod

### PR DESCRIPTION
**Pull request by Kabramen**
## About The Pull Request

Adds the sounding rod, which you can get via kink machine or loadout.  It basically works like the condom, however it doesn't comes off or leak any reagent after masturbating with, and can only be removed by the user with the arousal menu.
image
image
image
image
image
image
Also many thanks to @TotallyNotADog for drastically improving the rod sprites

This PR also fixes some typos in the condom code, also pointed out by @TotallyNotADog 

## Why It's Good For The Game

Uhh... 
M-muh RP and stuff?

## Changelog
:cl:
add: sounding rod
add: sounding rod for loaut and kink machine
/:cl:

### CODE REVIEW

**Comment by Kabramen** [comment]
One think that I forgot: currently it's possible to use a condom and a rod at the same time. While i don't thik that a problem (besides preventing to filling a condom with the rod also in, but that should be expected), i don't know how to make a check to prevent for both being used at the same time. If anyone knows how to, I'll gladly add it.

**Comment by quotefox** [comment]
Gross. kink shamed.

**Comment by Dahlular** [comment]
Not gross. Unkinkshamed.

**Review by Dahlular — APPROVED** [review]
owned, liked, and subscribed (quote don't kill me)

**Pull request merged**
