### PR TITLE
fixes comms agent + bioweapon scientist flavortext

### PR DESCRIPTION
**Pull request by TotallyNotADog**
## About The Pull Request
poss forgot to revert his changes in #707 so i've done a quick webedit to fix it

## Why It's Good For The Game
specifying company just increases the odds of conflicts with lore and RP, and the trade negotiations stuff just leaves a bad taste in my mouth.

## Changelog
:cl:
fix: fixed comms agent + bioweapon scientist flavortext
/:cl:

### CODE REVIEW

**Comment by ArchieBeepBoop** [comment]
Please.

**Comment by ArchieBeepBoop** [comment]
I would however keep the text about the bomb.

**Comment by quotefox** [comment]
Conflicting files, please fix!

**Comment by TotallyNotADog** [comment]
closing 'cause poss changed the description

**Pull request closed without merging**
