### PR TITLE
Emag fix

### PR DESCRIPTION
**Pull request by DragonTrance**
## About The Pull Request
Fixes the emag taking charges no matter what you used it on (unless thats a design choice). This should fix it, however emag_act() should return a value now if you want to take charge out if it, which I've changed for every device that can be emagged.

I've also changed how a few emag-able devices act from being emagged, but nothing insanely different.

## Why It's Good For The Game
Le fix

## Changelog
:cl:
fix: emag taking charges regardless of what you used it on
change: excessive variable changes in code/game/objects/items/RSF.dm
change: moves Emag() to emag_act() in code/game/objects/items/devices/lightreplacer.dm
change: punctuation in various files 
/:cl:

### CODE REVIEW

**Comment by DragonTrance** [comment]
Ree how are there conflicts

**Comment by DragonTrance** [comment]
Found it out and im gonna fix it later lol

**Comment by Dahlular** [comment]
Update your current branch to upstream and that should solve conflicts

**Comment by DragonTrance** [comment]
Yeah ik, just a severe lack of internet and me wanting to play hs13 is gettint in the way of me fixing this now lol

**Comment by DragonTrance** [comment]
Closing this for now until 1) i'm not fucking lazy and 2) until other prs get pulled because I dont wanna accidentally overwrite anything

**Pull request closed without merging**
