### PR TITLE
(CONFIG CHANGE) Updating Economy: Adding Paychecks, and makes Bank Accounts easier to work with

### PR DESCRIPTION
**Pull request by DragonTrance**
## About The Pull Request
Adds a passive "paycheck" system to jobs/ID cards, and makes bank accounts easier to work with. **Also updates configs/game_options.txt** by adding several config options for economy.

The amount of pay a single person gets from a paycheck scales depending on their job. For example:
Assistants get 49 credits per paycheck, and start off with 249 credits when they join the shift.
The captain gets 125 credits per paycheck, and starts off with 629 credits when they join the shift.

There are **new config options** in configs/game_options.txt, with the exception of items that you can buy, everything about the economy system is customizable. Don't like how much people get payed? You can change the base pay given to people, or simply make items from vending machines more expensive.

## Why It's Good For The Game
People are granted the ability to buy more expensive items over time, without affecting too much how they were able to buy items before. If you're wondering, the most expensive item is the industrial welding tool, sitting at 135 credits at the time of documenting this.

## Some screenshots of in-game vendors to show off prices
image
image
image
image

## Changelog
:cl:
add: Crew Members now acquire paychecks! Go out and buy things from the world, express your creativity by buying tons of food!
tweak: Item costs are now controlled by a config file
code: Makes Bank Accounts easier to work with, removes unused variables
config: Added several configurations to game_options.txt for economy and customizing economy
/:cl:

### CODE REVIEW

**Comment by TotallyNotADog** [comment]
Cool as hell. But maybe make the defines for paygrades something done via config files rather than defines? Idk, just thinking if the unlikely case that stuff will need to be fine tuned

**Comment by DragonTrance** [comment]
> Cool as hell. But maybe make the defines for paygrades something done via config files rather than defines? Idk, just thinking if the unlikely case that stuff will need to be fine tuned

Gonna add this, and a new element for things that should be priced because I can't exactly combine config stuff on the object variables

**Comment by DragonTrance** [comment]
sitting here

**Comment by Dahlular** [comment]
Okay one moment I goofed up lemme fix that

**Pull request merged**
