### PR TITLE
sm update ogg

### PR DESCRIPTION
**Pull request by Oposshim**
more dynamic sound effect when someone >Somehow< just licks/bumps the SM crystal (Will involve code later to make it more dynamic between players)

## About The Pull Request

Adding/working on sm sounds one step at a time w/ audio + code.

## Why It's Good For The Game

Immersion (again x2) 

## Changelog
:cl:
tweak: tweaked a few things
soundadd: added a new sound thingy
/:cl:

### CODE REVIEW

**Comment by TotallyNotADog** [comment]
so what exactly does the new sound actually sound like?

**Comment by yourdoom9898** [comment]
@TotallyNotADog To answer the question, in case you haven't heard it as is, the sound is a zapping/dusting sound with a loud scream

**Review by Dahlular — CHANGES_REQUESTED** [review]
I don't want items to scream when they hit the supermatter.

**Comment by ArchieBeepBoop** [comment]
True. A simple ishuman check would solve this.

**Comment by Oposshim** [comment]
back. time 2 mob check code

**Comment by ArchieBeepBoop** [comment]
> back. time 2 mob check code

I had an idea last time I saw this.
Instead of replacing the ogg, make it a separate sound and just make the SM check if it's a living/carbon and play that sound instead.

**Pull request closed without merging**
