### PR TITLE
Layenia TEG change / TEG Cold Tile Fix

### PR DESCRIPTION
**Pull request by ArchieBeepBoop**
## About The Pull Request

Changes the TEG chamber design slightly, instead making it a triple scrubber setup using injectors as outlets instead of passive vents.

Also fixes the tile that was causing engineering to go cold.

image

## Why It's Good For The Game

Passive vents seem to clog a fair bit in comparison to injectors. Injectors are the default outlet for all engines for a reason.

## Changelog
:cl:
tweak: Layenia TEG chamber atmos tweaks
fix: wrong planetary atmos tile in the TEG
/:cl:

### CODE REVIEW

**Comment by ToonClyde** [comment]
isn't the point of being Engineers to upgrade your stuff instead of just having it already upgraded at Round start??

**Comment by ArchieBeepBoop** [comment]
> isn't the point of being Engineers to upgrade your stuff instead of just having it already upgraded at Round start??

I modified this because the passive vent really does not cut in terms of volume transfer, also non-roundstart injectors require an air alarm associated with them. There's also a passive vent in the current map on top of the TEG burn chamber that doesn't connect to anything, which this PR eliminates.

**Comment by ToonClyde** [comment]
yeah I feel like the one injectors fine and I'm sorry for that leftover vent

**Review by Dahlular — APPROVED** [review]
MUSHROOM!

**Pull request merged**
