### PR TITLE
Adds departmental winter coats to loadout lists, adds cold protection to toggleable jackets

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request

Pre-existing job-/department-specific winter coats can now be taken in loadouts. Jackets of the /toggle/ type now grant the same cold protection as winter coats, in accordance with their flavour text.

## Why It's Good For The Game

**Adding coats to loadout options:** All the job-specific winter coats are readily available to those in a specific job. This is basically a convenience measure so that you don't need to head over to your department's 'Drobe to get a coat. Also, security winter coats were already in loadouts. Why not the others?
**Adding cold protection to jackets:** It struck me as odd that jackets with "fluffy collars" didn't help to keep you warm. On our current map, it makes sense for cold-proof jackets to be fairly common. In addition, these jackets are no better than just taking a winter coat (they're arguably worse due to the inability to protect your head) - all in all, this is just to widen the stylistic options available so that winter coats aren't the _only_ freely available warm clothes.

## Changelog
:cl:
tweak: Allowed job-/department-specific winter coats to be selected from the loadout.
tweak: Toggleable jackets now grant the same cold protection as winter coats.
/:cl:

### CODE REVIEW

**Comment by DragonTrance** [comment]
Blessed

**Comment by faaaay** [comment]
> 
> 
> Blessed

much appreciated

**Comment by Dahlular** [comment]
Please resolve conflicts before approval!

**Comment by faaaay** [comment]
> 
> 
> Please resolve conflicts before approval!

Voila!

**Review by Dahlular — APPROVED** [review]

**Pull request merged**
