### PR TITLE
When a penis is over 18 in. (Size 3), It will gib your partner during sex.

### PR DESCRIPTION
**Pull request by Orchidthederg**
## About The Pull Request

This PR adds the feature of Gibbing your partner if your penis is too large to fit. It has a cooldown, allowing you to pull out before ultimately ending your partner's life.

## Why It's Good For The Game

It would add more immersion to the erp side of the game, as well as balance erp.

## Changelog
:cl:
add: gibs partner when penis size is over 18 in. (size 3) during intercourse.
/:cl:

### CODE REVIEW

**Comment by ArchieBeepBoop** [comment]
lmaono

**Comment by ArchieBeepBoop** [comment]
based tho

**Comment by WTFIsmyname** [comment]
There's no way in hell this PR is going to get merged without some sort of perk or opt in for people that have no interest in it to avoid it

**Comment by Dahlular** [comment]
No.

**Comment by DragonTrance** [comment]
"Balance erp"
This is a great joke pr

**Comment by zeskorion** [comment]
18in is a bit small for gibbing

**Comment by Orchidthederg** [comment]
> 18in is a bit small for gibbing

hush maintainer

**Comment by Dahlular** [comment]
> > 18in is a bit small for gibbing
> 
> hush maintainer

Gonna close this thread since minors shouldn't be making PRs on our github anyways.

**Pull request closed without merging**
