### PR TITLE
Re-lowers bloodsucker chaos level

### PR DESCRIPTION
**Pull request by ArchieBeepBoop**
## About The Pull Request

Lowers the chaos level and requirements required for bloodsuckers

## Why It's Good For The Game

Let's not place the most interesting antag that we've had in a very long time on a high chaos level on par with nukies, wizards and others when they don't even have kill objectives nor are nowhere near as disruptive as the other antags on chaos level 4.

What is this, did someone get salty because they got bitten by a vampire and had to drink iron for a while? Jesus...

## Changelog
:cl:
balance: Bloodsuckers moved to chaos level 3.
/:cl:

### CODE REVIEW

**Comment by Dahlular** [comment]
uhhhhhhh to be fair I ended up killing all of sec and murdering half the station last time as a bloodsucker, so maybe it was a good idea. Unfair comparison. 
Though this is Jay's balance decision here, leave it up to them.

**Comment by ArchieBeepBoop** [comment]
> uhhhhhhh to be fair I ended up killing all of sec and murdering half the station last time as a bloodsucker, so maybe it was a good idea. Unfair comparison.
> Though this is Jay's balance decision here, leave it up to them.

I'm pretty sure any person that is as robust as you are can do that. The only counter to a robust person is a robust person.

Also, my personal opinion on antag balance is that one should actually play both antags and crew, never only one or the other so that they know their strengths and weaknesses by experience.

**Comment by Jay-Sparrow** [comment]
I had intention to bring it down to 3.5 and bring changelings up to 3.5

**Comment by Jay-Sparrow** [comment]
Also, you realize that those changes to threat requirements means they could drop with any population no matter how low, right?

**Comment by Dahlular** [comment]
> I'm pretty sure any person that is as robust as you are can do that. The only counter to a robust person is a robust person.
> 
> But yeah, bloodsucker is not a murderbone antag though, so for that to happen in the first place something must've gone pretty bad.
> 
> Also, my personal opinion on antag balance is that one should actually play both antags and crew, never only one or the other so that they know their strengths and weaknesses by experience before trying to balance them.

Yes, I play both antag and crew and have done plenty in the past, it is why I'm bringing this up in the first place. Obviously for an antag to go that far, things have to go really bad. You cannot deny the power level that a bloodsucker does have though; I personally think they're fine in this position because they've got some incredibly strong powers, but I do miss seeing them actually roll when we do get high-chaos rounds. Most of the issue with that is people simply just don't ready up.
Lowering the chaos level of bloodsuckers will just make them easier to access without keeping how out-of-control they can get in mind. I just hope this doesn't devolve into us leaning more towards gaming on this server-- which to be quite honest with you, that's not what a lot of people want. Antags are cool to have, but I don't wanna overdo it.

**Comment by ArchieBeepBoop** [comment]
> > I'm pretty sure any person that is as robust as you are can do that. The only counter to a robust person is a robust person.
> > But yeah, bloodsucker is not a murderbone antag though, so for that to happen in the first place something must've gone pretty bad.
> > Also, my personal opinion on antag balance is that one should actually play both antags and crew, never only one or the other so that they know their strengths and weaknesses by experience before trying to balance them.
> 
> Yes, I play both antag and crew and have done plenty in the past, it is why I'm bringing this up in the first place. Obviously for an antag to go that far, things have to go really bad. You cannot deny the power level that a bloodsucker does have though; I personally think they're fine in this position because they've got some incredibly strong powers, but I do miss seeing them actually roll when we do get high-chaos rounds. Most of the issue with that is people simply just don't ready up.
> Lowering the chaos level of bloodsuckers will just make them easier to access without keeping how out-of-control they can get in mind. I just hope this doesn't devolve into us leaning more towards gaming on this server-- which to be quite honest with you, that's not what a lot of people want. Antags are cool to have, but I don't wanna overdo it.

They may have strong powers, yet honestly they're just as disruptive in my opinion as a traitor who knows how to use eldritch affairs. I do not think it justifies them being locked to chaos 4.

At that point we might as well lock all the antags at high chaos due to the pretense that everyone's just going to game then. If people want extended, they can already vote 0 and 1 which already pull the entire vote pool down. I believe 3 is and should always be the magic number for more interesting antags such as the bloodsuckers.

**Comment by Dahlular** [comment]
> They may have strong powers, yet honestly they're just as disruptive in my opinion as a traitor who knows how to use eldritch affairs. I do not think it justifies them being locked to chaos 4.
> 
> At that point we might as well lock all the antags at high chaos due to the pretense that everyone's just going to game then. If people want extended, they can already vote 0 and 1 which already pulls the entire vote pool down. I believe 3 is and should always be the magic number for more interesting antags such as the bloodsuckers.

Now, there's no need to take what I said out of where it belongs and keep pushing it. It's all about balance. Like I said before, this is Jay's balance decision primarily, but I am weighing in as I am the one who has played the antag, and plays crew often as well. I'm unsure if you can say the same for yourself.
Bloodsuckers are in a rather grey area as it stands right now, and I don't believe we have enough evidence with bloodsucker rounds to justify any balance change. I can see where you're coming from, and I think it'd be a good idea-- but there's a lot to consider with the playerbase side of things, like I've mentioned. Probably wait on this.

**Comment by MalricB** [comment]
> > They may have strong powers, yet honestly they're just as disruptive in my opinion as a traitor who knows how to use eldritch affairs. I do not think it justifies them being locked to chaos 4.
> > At that point we might as well lock all the antags at high chaos due to the pretense that everyone's just going to game then. If people want extended, they can already vote 0 and 1 which already pulls the entire vote pool down. I believe 3 is and should always be the magic number for more interesting antags such as the bloodsuckers.
> 
> Now, there's no need to take what I said out of where it belongs and keep pushing it. It's all about balance. Like I said before, this is Jay's balance decision primarily, but I am weighing in as I am the one who has played the antag, and plays crew often as well. I'm unsure if you can say the same for yourself.
> Bloodsuckers are in a rather grey area as it stands right now, and I don't believe we have enough evidence with bloodsucker rounds to justify any balance change. I can see where you're coming from, and I think it'd be a good idea-- but there's a lot to consider with the playerbase side of things, like I've mentioned. Probably wait on this.

Why is someone who never played an antag making balance decisions though?

**Comment by Dahlular** [comment]
> 
> Why is someone who never played an antag making balance decisions though?

why do you think i'm weighing in you dipshit

**Comment by Dahlular** [comment]
Dunno, rather inconclusive.

**Pull request closed without merging**
