### PR TITLE
Fixes a couple nagging issues with the Space Hermit

### PR DESCRIPTION
**Pull request by CapnMachaddish**
## About The Pull Request

After substantial complaints from the handful of people who actually play Space Hermit, I've done a couple things to make it still challenging but less of a fucking nuisance. The Science Protolathe board they get has been swapped for an Omni Protolathe board mainly for access to some medical supplies later on, and a canister of air has been added to the crashed shuttle, to help with the frustrating "voiding problem" that makes it virtually impossible to mine the hermit asteroid without draining all of your air every time you break a rock.

## Why It's Good For The Game

Ghost roles are designed for people to have fun without being subject to all of the same strictures that apply to stationside life, but playing space hermit wasn't really a whole lot of fun when you had to risk life and limb every time you wanted to mine even a single tile of rock. With any luck, this should make playing hermit more enjoyable again, yet still challenging.

## Changelog
:cl:
add: omnilathe board
del: sci lathe board
add: airmix canister
/:cl:

### CODE REVIEW

**Comment by ArchieBeepBoop** [comment]
I usually exclusively reserve the omnilathe board for ghost roles that have more than a single slot. The scilathe one already has access to a circuit printer that can print chem dispensers/masters/heaters so adding that for healing is kinda.. moot.

**Comment by CapnMachaddish** [comment]
Hm fair enough. Still worth merging the air tank to cut down on the voiding problem though.

**Comment by CapnMachaddish** [comment]
This should be ready to merge now, I got rid of the omnilathe board.

**Comment by CapnMachaddish** [comment]
Closing this to make a better version, hold on.

**Pull request closed without merging**
